name: Compile and Push BRid37 opAIO Fork

on:
  push:
    branches: [ bp-BPilot-BANNABLE ]
  pull_request:
    branches: [ bp-BPilot-BANNABLE ]
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for manual run'
        required: false
        default: 'Manual trigger'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        repository: BRid37/opAIO
        ref: bp-BPilot-BANNABLE
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          ca-certificates \
          clang \
          cppcheck \
          build-essential \
          gcc-arm-none-eabi \
          liblzma-dev \
          capnproto \
          libcapnp-dev \
          curl \
          libcurl4-openssl-dev \
          git \
          git-lfs \
          ffmpeg \
          libavformat-dev \
          libavcodec-dev \
          libavdevice-dev \
          libavutil-dev \
          libavfilter-dev \
          libbz2-dev \
          libeigen3-dev \
          libffi-dev \
          libglew-dev \
          libgles2-mesa-dev \
          libglfw3-dev \
          libglib2.0-0 \
          libqt5charts5-dev \
          libncurses5-dev \
          libssl-dev \
          libusb-1.0-0-dev \
          libzmq3-dev \
          libzstd-dev \
          libsqlite3-dev \
          libsystemd-dev \
          locales \
          opencl-headers \
          ocl-icd-libopencl1 \
          ocl-icd-opencl-dev \
          portaudio19-dev \
          qml-module-qtquick2 \
          qtmultimedia5-dev \
          qtdeclarative5-dev \
          qttools5-dev-tools \
          libqt5svg5-dev \
          libqt5serialbus5-dev \
          libqt5x11extras5-dev \
          libqt5opengl5-dev \
          qtbase5-dev \
          qtchooser \
          qt5-qmake \
          qtbase5-dev-tools \
          python3-dev \
          python3-venv

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        # Include specific versions of required libraries
        pip install pyobjc_framework_CoreSpotlight==10.3.1 setuptools==71.1.0 azure_identity==1.17.1 pyobjc_framework_eventkit==10.3.1 pyobjc_framework_coretext==10.3.1 pyobjc_framework_Speech==10.3.1 python-dateutil==2.9.0 opencv_python_headless==4.10.0 pyreadline3==3.4.1 nodeenv==1.9.1 pyobjc_framework_SafetyKit==10.3.1 pyobjc_framework_UniformTypeIdentifiers==10.3.1 yarl==1.9.4 pyobjc_framework_servicemanagement==10.3.1 pyobjc_framework_accessibility==10.3.1 sortedcontainers==2.4.0 pyobjc_framework_CoreData==10.3.1 pyobjc_framework_CoreHaptics==10.3.1 pyobjc_framework_Cocoa==10.3.1 pyobjc_framework_QuickLookThumbnailing==10.3.1 pyobjc_framework_Virtualization==10.3.1 pyobjc_framework_OSAKit==10.3.1 pytest_cpp==2.5.0 pylibsrtp==0.10.0 mkdocs_get_deps==0.2.0 pyobjc_framework_kernelmanagement==10.3.1 pyobjc_framework_PencilKit==10.3.1 pyobjc_framework_IOBluetoothUI==10.3.1 PyAutoGUI==0.9.54 cffi==1.16.0 pyobjc_framework_videotoolbox==10.3.1 pyobjc_framework_ScreenTime==10.3.1 python_dateutil==2.9.0 smbus2==0.4.3 pyobjc_framework_SyncServices==10.3.1 pyobjc_framework_FileProvider==10.3.1 execnet==2.1.1 pytest_xdist==3.6.1 websocket_client==1.8.0 pyobjc_framework_symbols==10.3.1 pyobjc_framework_mediaaccessibility==10.3.1 pyobjc_framework_iosurface==10.3.1 libusb1==3.1.0 pyobjc_framework_OSLog==10.3.1 pyobjc_framework_CoreMIDI==10.3.1 pyobjc_framework_soundanalysis==10.3.1 shapely==2.0.5 pyobjc_framework_MetalPerformanceShaders==10.3.1 pandas==2.2.2 zstandard==0.23.0 mergedeep==1.3.4 mkdocs==1.6.0 pyobjc_framework_applescriptkit==10.3.1 pyobjc_framework_ExternalAccessory==10.3.1 isodate==0.6.1 pyobjc_framework_PHASE==10.3.1 aiortc==1.9.0 aiosignal==1.3.1 pyobjc_framework_replaykit==10.3.1 pyobjc_framework_MediaPlayer==10.3.1 sounddevice==0.4.7 coloredlogs==15.0.1 pytest-mock==3.14.0 pyobjc_framework_AutomaticAssessmentConfiguration==10.3.1 pyobjc_framework_libxpc==10.3.1 pyobjc_framework_intents==10.3.1 pyobjc_framework_extensionkit==10.3.1 pyobjc_framework_securityinterface==10.3.1 pyobjc_framework_cfnetwork==10.3.1 pyobjc_framework_LinkPresentation==10.3.1 PyRect==0.2.0 zipp==3.19.2 pygments==2.18.0 pyobjc_framework_sharedwithyoucore==10.3.1 numpy==1.26.4 identify==2.6.0 pyobjc_framework_ColorSync==10.3.1 pyobjc_framework_CoreBluetooth==10.3.1 ifaddr==0.2.0 seaborn==0.13.2 pyobjc_framework_usernotifications==10.3.1 pyobjc_framework_Intents==10.3.1 pyobjc_framework_Quartz==10.3.1 pyobjc_framework_browserenginekit==10.3.1 pyobjc_framework_NetFS==10.3.1 pyobjc_framework_Photos==10.3.1 pyobjc_framework_shazamkit==10.3.1 pyobjc_framework_iobluetooth==10.3.1 pyobjc_framework_latentsemanticmapping==10.3.1 pyobjc_framework_MLCompute==10.3.1 pyparsing==3.1.2 charset_normalizer==3.3.2 pyobjc_framework_MediaLibrary==10.3.1 lxml==5.2.2 pyobjc_framework_DeviceCheck==10.3.1 pyobjc_framework_pencilkit==10.3.1 pyobjc_framework_externalaccessory==10.3.1 pyobjc_framework_calendarstore==10.3.1 pyobjc_framework_gamecenter==10.3.1 pyobjc_framework_cinematic==10.3.1 pyobjc_framework_fsevents==10.3.1 pyobjc_framework_metalfx==10.3.1 pycapnp==2.0.0 MarkupSafe==2.1.5 pyobjc_framework_corespotlight==10.3.1 pyobjc_framework_intentsui==10.3.1 pytest-timeout==2.3.1 pyobjc_framework_osakit==10.3.1 pyobjc_framework_BusinessChat==10.3.1 pyobjc_framework_launchservices==10.3.1 pyobjc_framework_mediatoolbox==10.3.1 Farama_Notifications==0.0.4 json_rpc==1.15.0 attrs==23.2.0 pyobjc_framework_metal==10.3.1 pyobjc_framework_datadetection==10.3.1 pyobjc_framework_IOBluetooth==10.3.1 PyGetWindow==0.0.9 azure_core==1.30.2 pyobjc_framework_audiovideobridging==10.3.1 azure_storage_blob==12.21.0 natsort==8.4.0 panda3d-simplepbr==0.12.0 pyobjc_framework_SafariServices==10.3.1 pyobjc_framework_Accessibility==10.3.1 pyobjc_framework_LaunchServices==10.3.1 pyobjc_framework_GameKit==10.3.1 pyarrow==17.0.0 pyobjc_framework_Metal==10.3.1 aiohttp==3.9.5 cfgv==3.4.0 pyobjc_framework_coredata==10.3.1 pyobjc_framework_diskarbitration==10.3.1 pytest_subtests==0.13.1 pycryptodome==3.20.0 pyobjc_framework_Automator==10.3.1 pyobjc_framework_MetalKit==10.3.1 six==1.16.0 ruff==0.5.5
        if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi
        if [ -f "openpilot/requirements.txt" ]; then pip install -r openpilot/requirements.txt; fi

    - name: Build opAIO
      run: |
        scons -j$(nproc)

    - name: Commit and push compiled files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Add compiled version [skip ci]" || echo "No changes to commit"
        git push

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
