name: Create Branch and Setup Sync Workflow

on:
  workflow_dispatch:
    inputs:
      remote_repo_url:
        description: 'Remote Repository URL'
        required: true
      remote_branch_name:
        description: 'Remote Branch Name'
        required: true
      new_branch_name:
        description: 'New Branch Name'
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          ref: main
      - name: Create Sync Workflow File in Main Branch
        run: |
          mkdir -p .github/workflows
          secret_placeholder='$'"{${{ '{' }} secrets.PAT ${{ '}' }}}"
          cat << EOF > .github/workflows/sync_${{ github.event.inputs.new_branch_name }}.yml
          name: Sync ${{ github.event.inputs.new_branch_name }}
      
          on:
            schedule:
              - cron: "0 9 * * *"
            workflow_dispatch:
      
          jobs:
            sync:
              runs-on: ubuntu-latest
              steps:
                - uses: actions/checkout@v4
                  with:
                    ref: ${{ github.event.inputs.new_branch_name }}
                    persist-credentials: false
                - name: Sync with Remote Repo
                  uses: repo-sync/github-sync@v2.3.0
                  with:
                    source_repo: "${{ github.event.inputs.remote_repo_url }}"
                    source_branch: "${{ github.event.inputs.remote_branch_name }}"
                    destination_branch: "${{ github.event.inputs.new_branch_name }}"
                    github_token: $secret_placeholder
          EOF

                

        
      - name: Commit and Push Workflow File to Main Branch
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          git config --global user.name 'BRid37'
          git config --global user.email '55640145+BRid37@users.noreply.github.com'
          git add .github/workflows/sync_${{ github.event.inputs.new_branch_name }}.yml
          git commit -m "Add sync workflow for ${{ github.event.inputs.new_branch_name }}"
          git push origin main
          
      - name: Checkout and Push New Branch
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          # Setup git configuration
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # Create and switch to a new branch locally
          git checkout -b ${{ github.event.inputs.new_branch_name }}
          
          # Push the new branch to the repository
          git push origin ${{ github.event.inputs.new_branch_name }}

      - name: Trigger the Workflow
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.PAT }}" \
            https://api.github.com/repos/BRid37/opAIO/actions/workflows/sync_${{ github.event.inputs.new_branch_name }}.yml/dispatches \
            -d '{"ref":"main"}'


          

          
      

        




