name: Revert Commit After Sync

on:
  workflow_run:
    workflows: ["Sync FrogPilot-Staging"]
    types:
      - completed
  workflow_dispatch:

jobs:
  revert-commit:
    runs-on: ubuntu-latest
    steps:

      - name: Configure Git to skip symlinks
        run: git config --global core.symlinks false
        
      - name: Checkout repo without symlinks
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure you fetch all history for commits, tags, etc
          persist-credentials: false

      - name: Setup Git Config
        run: |
          git config --global user.email "55640145+BRid37@users.noreply.github.com"
          git config --global user.name "BRid37"

      - name: Ensure clean state
        run: |
          git checkout fp-FrogPilot-Staging
          git fetch origin fp-FrogPilot-Staging
          git reset --hard origin/fp-FrogPilot-Staging
          git clean -fdx

      - name: Find commit hash by name and revert
        run: |
          git log --oneline --first-parent --grep "Compile FrogPilot" fp-FrogPilot-Staging > log.txt
          commit=$(cat log.txt | head -n 1 | cut -d " " -f 1)
          echo "Commit to revert: $commit"
          git revert $commit

      - name: Cherry-pick commit
        run: |
          git cherry-pick 9827d344088aa94657fbf878f605d3066314ac39 || true
          git cherry-pick 46cecf31253fe5a573c83c09cad5cfd05609f05e || true
          git cherry-pick 88aad794038e1d37cf36c1982c8c69d960c19f85 || true
          git cherry-pick 36000fe61f27231b143ceb37cbafdf563814fbc5 || true
          git cherry-pick b3985e337ad68434373b06271eaf3851fe6a53b4 || true
        continue-on-error: true
      - name: Push changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin fp-FrogPilot-Staging

