name: Revert Commit After Sync

on:
  workflow_run:
    workflows: ["Sync FrogPilot-Staging"]
    types:
      - completed
  workflow_dispatch:

jobs:
  revert-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git to skip symlinks
        run: git config --global core.symlinks false
        
      - name: Checkout repo without symlinks
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure you fetch all history for commits, tags, etc
          persist-credentials: false

      - name: Setup Git Config
        run: |
          git config --global user.email "55640145+BRid37@users.noreply.github.com"
          git config --global user.name "BRid37"

      - name: Ensure clean state
        run: |
          git checkout fp-FrogPilot-Staging
          git fetch origin fp-FrogPilot-Staging
          git reset --hard origin/fp-FrogPilot-Staging
          git clean -fdx

      - name: Find compile commit and revert changes
        run: |
          # Find the commit hash for the "Compile FrogPilot" commit
          compile_commit=$(git log --oneline --first-parent --grep "Compile FrogPilot" fp-FrogPilot-Staging | head -n 1 | cut -d " " -f 1)
          echo "Compile commit to revert: $compile_commit"
          
          # Get all commits after the compile commit
          commits_after_compile=$(git rev-list $compile_commit..HEAD | tail -n +2 | tac)
          
          # Revert all commits after the compile commit
          if [ ! -z "$commits_after_compile" ]; then
            for commit in $commits_after_compile; do
              echo "Reverting commit: $commit"
              git revert --no-commit $commit || git revert --abort
            done
          fi

          # Revert the compile commit itself
          git revert --no-edit $compile_commit

          # Re-apply all commits that were reverted in the first step
          if [ ! -z "$commits_after_compile" ]; then
            for commit in $commits_after_compile; do
              echo "Re-applying commit: $commit"
              git cherry-pick $commit || git cherry-pick --abort
            done
          fi

      - name: Cherry-pick commits
        run: |
          git cherry-pick 9827d344088aa94657fbf878f605d3066314ac39 || git cherry-pick --abort
          git cherry-pick 46cecf31253fe5a573c83c09cad5cfd05609f05e || git cherry-pick --abort
          git cherry-pick 88aad794038e1d37cf36c1982c8c69d960c19f85 || git cherry-pick --abort
          git cherry-pick 36000fe61f27231b143ceb37cbafdf563814fbc5 || git cherry-pick --abort
          git cherry-pick b3985e337ad68434373b06271eaf3851fe6a53b4 || git cherry-pick --abort

      - name: Push changes
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin fp-FrogPilot-Staging
