name: Sync FrogPilot-Staging

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: repo-sync
        uses: repo-sync/github-sync@v2.3.0
        with:
          source_repo: "https://github.com/FrogAi/FrogPilot.git"
          source_branch: "FrogPilot-Staging"
          destination_branch: "fp-FrogPilot-Staging"
          github_token: ${{ secrets.PAT }}
