name: Sync kp-KisaPilot

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: kp-KisaPilot
          persist-credentials: false
      - name: Sync with Remote Repo
        uses: repo-sync/github-sync@v2.3.0
        with:
          source_repo: "https://github.com/kisapilot/openpilot.git"
          source_branch: "KisaPilot"
          destination_branch: "kp-KisaPilot"
          github_token: ${{ secrets.PAT }}
