name: Sync hp-Hpilot-LKAS-BANNABLE

on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: hp-Hpilot-LKAS-BANNABLE
          persist-credentials: false
      - name: Sync with Remote Repo
        uses: repo-sync/github-sync@v2.3.0
        with:
          source_repo: "https://github.com/CHaucke89/Hpilot"
          source_branch: "Hpilot-LKAS"
          destination_branch: "hp-Hpilot-LKAS-BANNABLE"
          github_token: ${{ secrets.PAT }}
